// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebaseプロジェクトの設定クラス
/// 注意：このファイルは仮の設定です。実際のFirebaseプロジェクトを作成後、
/// flutterfire configureコマンドで自動生成されたファイルに置き換えてください
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web設定
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClIA2_3fHJuHoOKY5AVG1OXdpIyJTkqy0',
    appId: '1:788143974236:web:YOUR-WEB-APP-ID',
    messagingSenderId: '788143974236',
    projectId: 'waselab-30308',
    authDomain: 'waselab-30308.firebaseapp.com',
    storageBucket: 'waselab-30308.firebasestorage.app',
  );

  // Android設定
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCffoMNl-fzWljHKHoqwzIuc5jas042aJA',
    appId: '1:788143974236:android:6246f4d13556d4b6000399',
    messagingSenderId: '788143974236',
    projectId: 'waselab-30308',
    storageBucket: 'waselab-30308.firebasestorage.app',
  );

  // iOS設定
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClIA2_3fHJuHoOKY5AVG1OXdpIyJTkqy0',
    appId: '1:788143974236:ios:9859b91f3880f3df000399',
    messagingSenderId: '788143974236',
    projectId: 'waselab-30308',
    iosBundleId: 'com.kosukeonishi.experimentCooperationApp',
    storageBucket: 'waselab-30308.firebasestorage.app',
    iosClientId: '788143974236-5m4bv0dspcbl2bquevs6ssgh088413rh.apps.googleusercontent.com',
  );

  // macOS設定
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClIA2_3fHJuHoOKY5AVG1OXdpIyJTkqy0',
    appId: '1:788143974236:ios:9859b91f3880f3df000399',
    messagingSenderId: '788143974236',
    projectId: 'waselab-30308',
    iosBundleId: 'com.kosukeonishi.experimentCooperationApp',
    storageBucket: 'waselab-30308.firebasestorage.app',
    iosClientId: '788143974236-5m4bv0dspcbl2bquevs6ssgh088413rh.apps.googleusercontent.com',
  );

  // Windows設定
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClIA2_3fHJuHoOKY5AVG1OXdpIyJTkqy0',
    appId: '1:788143974236:web:YOUR-WINDOWS-APP-ID',
    messagingSenderId: '788143974236',
    projectId: 'waselab-30308',
    authDomain: 'waselab-30308.firebaseapp.com',
    storageBucket: 'waselab-30308.firebasestorage.app',
  );
}
